misc changes to scripts
change check-updates script to be a bit better readble and using 'checkupdates' from contrib. i3sounds and checkupdates scripts now will not run if the needed dependencies are not met. removed the frame from notifications. note: checkupdates script still need some testing.

diff --git a/airootfs/etc/skel/.config/i3/config.d/scripts/check-updates b/airootfs/etc/skel/.config/i3/config.d/scripts/check-updates
--- a/airootfs/etc/skel/.config/i3/config.d/scripts/check-updates
+++ b/airootfs/etc/skel/.config/i3/config.d/scripts/check-updates
@@ -1,17 +1,60 @@
 #!/usr/bin/sh
 #
-# super simple script to check for arch updates
+# super simple script to check for arch updates. uses 'checkupdates' from pacman-contrib
 
-pkexec sh -c "yay -Sy"
-archUpdatesNumber=$(yay -Qqu | wc -l)
-archUpdatesPkg=$(yay -Qqu)
+# check if dependencies are met
+dependencies=("pacman-contrib" "yay")
+for pkg in ${dependencies[@]}; do
+  checkDependency=$(pacman -Q $pkg)
+  exitStatus=$?
+  if [ "$exitStatus" -eq 1 ]; then
+    notify-send "Error !" "Please install '$pkg' to check for updates"
+    echo "Error ! Please install '$pkg'"
+    exit 2
+  fi
+done
 
-if [[ $archUpdatesNumber -gt 0 ]]; then
-  notify-send "Updates Available" "Total: $archUpdatesNumber\n$archUpdatesPkg"
-  echo "Updates Available"
-  echo "Total: $archUpdatesNumber"
-  echo $archUpdatesPkg
-else
-  notify-send "No Updates Available" ""
-  echo "No Updates Available" ""
+notify-send -t 750 "Getting Updates..."
+echo "Getting Updates..."
+
+updates () {
+  updates=$(checkupdates)
+  updatesExitStatus=$?
+  if [ "$updatesExitStatus" -eq 0 ]; then
+    updatesNumber=$(checkupdates | wc -l)
+    notify-send "Updates Available" "Total: $updatesNumber\n$updates"
+    echo "Updates Available, Total: $updatesNumber"
+    echo "$updates"
+    updatesExit=0
+  else
+    notify-send "No Updates Available" ""
+    echo "No Updates Available."
+    updatesExit=2
+  fi
+}
+
+updatesAUR () {
+  updatesAUR=$(yay -Sua)
+  exitStatus=$?
+  if [ "$exitStatus" -eq 1 ]; then
+    notify-send "AUR Updates Available" "$updatesAUR"
+    echo "AUR Updates Available."
+    echo "$updatesAUR"
+    updatesAURExit=0
+  else
+    notify-send "No AUR Updates Available" ""
+    echo "No AUR Updates Available."
+    updatesAURExit=2
+  fi
+}
+
+updates
+updatesAUR
+
+if [ "$updatesExit" -eq 0 ] || [ "$updatesAURExit" -eq 0 ]; then
+    exit 0
+  else
+    exit 2
 fi
+
+exit 2
diff --git a/airootfs/etc/skel/.config/i3/config.d/scripts/i3sounds b/airootfs/etc/skel/.config/i3/config.d/scripts/i3sounds
--- a/airootfs/etc/skel/.config/i3/config.d/scripts/i3sounds
+++ b/airootfs/etc/skel/.config/i3/config.d/scripts/i3sounds
@@ -1,6 +1,18 @@
 #!/bin/bash
 # yaru sounds is from ubuntu. I got it from this git repo: https://github.com/ubuntu/yaru. thanks!
 
+# check if dependencies are met
+dependencies=("libpulse")
+for pkg in ${dependencies[@]}; do
+  checkDependency=$(pacman -Q $pkg)
+  exitStatus=$?
+  if [ "$exitStatus" -eq 1 ]; then
+    notify-send "Error !" "Please install '$pkg' to play notification sound or change the default player in i3sounds"
+    echo "Error ! Please install '$pkg' to play notification sound or change the default player in i3sounds"
+    exit 2
+  fi
+done
+
 player=paplay
 soundsFolder=~/.config/i3/config.d/scripts/i3sounds.d/yaru
 case "$1" in
